// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
  function throttle(func, delay) {
    let isThrottled = false;

    return () => {
      if (!isThrottled) {
        func();
        isThrottled = true;
        setTimeout(() => {
          isThrottled = false;
        }, delay);
      }
    };
  }
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function PrimaryNavScript() {
	// BEGIN USER CODE
  try {
    const getDataSetHeight = (element) => Number(element?.dataset?.height || "");
    const handleResize = () => {
      const topSection = document.querySelector(".top-section");
      const bottomSection = document.querySelector(".nav-bottom-section");
      const leftNav = document.querySelector(".application-frame-left-nav");
      const secondaryNavBottom = document.querySelector(
        ".nav-bottom-section .secondary-nav"
      );
      const moreBtn = document.querySelector(".more-button");

      const topSectionHeight = topSection?.offsetHeight + 48;
      const totalHeight = document?.documentElement?.clientHeight || 0;

      if (!getDataSetHeight(bottomSection)) {
        bottomSection?.setAttribute("data-height", bottomSection?.offsetHeight);
      }

      if (topSectionHeight + getDataSetHeight(bottomSection) > totalHeight) {
        secondaryNavBottom?.classList.add("hide-nav");
        moreBtn?.classList.remove("hide");
      } else {
        secondaryNavBottom?.classList.remove("hide-nav");
        moreBtn?.classList.add("hide");
        leftNav?.classList.remove("mid-expanded-nav");
      }

      if (totalHeight > 300) {
        leftNav?.classList.remove("full-expanded-nav");
      } else {
          leftNav?.classList.remove("mid-expanded-nav");
      }
    };

    const throttledResize = throttle(handleResize, 250);

    const handlePrimaryNavEvents = () => {
      const leftNav = document.querySelector(".application-frame-left-nav");
      const menuExpand = document.querySelector(".menu-expand");
      const menuCollapse = document.querySelector(".menu-collapse");
      const moreBtn = document.querySelector(".more-button");

      menuExpand?.addEventListener("click", () => {
        leftNav?.classList.add("full-expanded-nav");
      });

      menuCollapse?.addEventListener("click", () => {
        leftNav?.classList.remove("full-expanded-nav");
      });

      moreBtn?.addEventListener("click", () => {
        leftNav?.classList.toggle("mid-expanded-nav");
      });

      document.addEventListener("click", function (event) {
        const outsideClick = !leftNav?.contains(event.target);

        if (outsideClick) {
          leftNav?.classList.remove("full-expanded-nav", "mid-expanded-nav");
        }
      });
    };

    handleResize();
    handlePrimaryNavEvents();
    window?.addEventListener("resize", throttledResize);
  } catch(e) {
	  console.log('Error with primary nav', e)
  }
	// END USER CODE
}
