// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE

const indicatorMap = {
    basic: createBasicIndicator,
    circular: createCircularIndicator,
    linearIndeterminate(loadingText) {
        return createLinearIndicator('indeterminate', loadingText);
    },
    linearQuery(loadingText) {
        return createLinearIndicator('query', loadingText);
    }
};

function createBasicIndicator(loadingText) {
    const outer = document.createElement('div');
    outer.innerHTML = `<span class="mx-text basic-loading-indicator disw-progress loading" aria-hidden="true">${loadingText || 'Loading'}</span><span class="sr-only">${loadingText}</span>`

    return outer;
}

function createCircularIndicator(loadingText) {
    const size = 'md';
    const outer = document.createElement('div');
    outer.classList.add('circular-loading-indicator', 'disw-progress', size);
    outer.innerHTML = `<div class="spinner"><span class="sr-only">${loadingText}</span></div>`

    return outer;
}

function createLinearIndicator(type = 'indeterminate', loadingText) {
    const outer = document.createElement('div');
    outer.classList.add('widget-progress-bar', 'disw-progress', type, 'progress-bar-small');
    outer.innerHTML = `<div class="progress"><span class="sr-only">${loadingText}</span><div class="progress-bar" style="width: 10%;"></div></div>`;

    return outer;
}

function createOverlay() {
    const overlay = document.createElement('div');
    overlay.classList.add('mx-underlay');

    return overlay;
}

function createIndicatorInOverlay({ indicator, loadingText }) {
    const progress = document.createElement('div');
    progress.classList.add('mx-progress', 'disw-progress');

    if(loadingText && loadingText.length) {
        progress.innerHTML = `<div class="mx-progress-message">${loadingText}</div>`;
    }

    progress.appendChild(indicator);

    return progress;
}

mx.ui.ShowDISWProgress = ShowDISWProgress;

// END EXTRA CODE

/**
 * @param {"Siemens_UI_Module.loaderTypes.circular"|"Siemens_UI_Module.loaderTypes.linearIndeterminate"|"Siemens_UI_Module.loaderTypes.linearDeterminate"|"Siemens_UI_Module.loaderTypes.linearQuery"|"Siemens_UI_Module.loaderTypes.basic"} [loaderType]
 * @param {string} [targetSelector]
 * @param {string} [loadingText]
 * @returns {Promise.<void>}
 */
export async function ShowDISWProgress(loaderType, targetSelector, loadingText) {
	// BEGIN USER CODE
    const indicatorCreator = indicatorMap[loaderType];
    const target = targetSelector || 'body';
    const container = document.querySelector(target);

    if(!indicatorCreator) {
        return;
    }

    if(!container) {
        throw new Error('Missing container element!');

        return;
    }

    if(target === 'body') {
        document.querySelector('.loader-container-blocking').appendChild(createOverlay());
        document.querySelector('.loader-container-blocking').appendChild(createIndicatorInOverlay({ indicator: indicatorCreator?.(loadingText ? '' : 'Loading Data'), loadingText } ));

        return;
    }

    document.querySelector(target).appendChild(indicatorCreator?.(loadingText))
	// END USER CODE
}
