// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function ShowTooltip() {
	// BEGIN USER CODE
document.querySelectorAll('.disw-card-content h4').forEach((item) => {
    if(item.offsetHeight > 57) {
        item.setAttribute('title', item.textContent);
        item.classList.add('clamp');
    }
})
	// END USER CODE
}
