// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
document.addEventListener('click', e => {
	const element = document.querySelector('.navigation-panel');
    if (!element?.contains(e.target)) {
		document.querySelector('.secondary-nav .active')?.classList.remove('active');
		document.querySelector('.navigation-panel')?.classList.remove('open')
	};
});
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function ShowNavigationPanel() {
	// BEGIN USER CODE

	document.activeElement.classList.toggle('active');
	document.querySelector('.navigation-panel')?.classList.toggle('open');
	
	// END USER CODE
}
