// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package adminessentials.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;

public class JAVA_Email_Generate_EML extends UserAction<IMendixObject>
{
	/** @deprecated use Email.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Email;
	private final adminessentials.proxies.Email Email;
	/** @deprecated use EmailTemplate.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __EmailTemplate;
	private final adminessentials.proxies.EmailTemplate EmailTemplate;
	/** @deprecated use com.mendix.utils.ListUtils.map(Recipients, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __Recipients;
	private final java.util.List<administration.proxies.Account> Recipients;

	public JAVA_Email_Generate_EML(
		IContext context,
		IMendixObject _email,
		IMendixObject _emailTemplate,
		java.util.List<IMendixObject> _recipients
	)
	{
		super(context);
		this.__Email = _email;
		this.Email = _email == null ? null : adminessentials.proxies.Email.initialize(getContext(), _email);
		this.__EmailTemplate = _emailTemplate;
		this.EmailTemplate = _emailTemplate == null ? null : adminessentials.proxies.EmailTemplate.initialize(getContext(), _emailTemplate);
		this.__Recipients = _recipients;
		this.Recipients = java.util.Optional.ofNullable(_recipients)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(recipientsElement -> administration.proxies.Account.initialize(getContext(), recipientsElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext ctx = getContext();

		// === 1. Extract data ===
		String contentType = EmailTemplate.getContentType().toString();
		String template = EmailTemplate.getTemplate();
		String recipientType = Email.getRecipientType().toString();
		String subject = Email.getSubject() != null ? Email.getSubject() : "Email";

		// === 2. Resolve recipients from parameter ===
		java.util.List<String> recipientList = new java.util.ArrayList<>();
		for (administration.proxies.Account acc : Recipients) {
			if (acc.getEmail() != null && !acc.getEmail().isEmpty()) {
				// All recipients in TO for now — can be extended with recipientType
				recipientList.add(acc.getEmail());
			}
		}
		if (recipientList.isEmpty()) {
			throw new com.mendix.systemwideinterfaces.MendixRuntimeException("No recipients found with Email attribute");
		}

		// === 3. Generate EML content ===
		StringBuilder eml = new StringBuilder();
		eml.append(recipientType + ": ").append(String.join(";", recipientList)).append("\r\n");
		eml.append("Subject: ").append(subject).append("\r\n");
		eml.append("X-Unsent: 1").append("\r\n");
		eml.append("MIME-Version: 1.0\r\n");
		eml.append("Content-Type: text/" + contentType + "; charset=\"UTF-8\"\r\n");
		eml.append("Content-Transfer-Encoding: 8bit\r\n");
		eml.append("\r\n"); // empty line separating headers from body
		eml.append(template);
		LOG.info(eml.toString());

		// === 4. Store EML in file ===
		byte[] contentBytes = eml.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
		java.io.InputStream stream = new java.io.ByteArrayInputStream(contentBytes);
		Email.getMendixObject().setValue(ctx, "Name", subject.replaceAll("[^a-zA-Z0-9-_ ]", "") + ".eml");
		com.mendix.core.Core.storeFileDocumentContent(ctx, Email.getMendixObject(), stream);

		return Email.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JAVA_Email_Generate_EML";
	}

	// BEGIN EXTRA CODE
	public static ILogNode LOG = Core.getLogger("TEST");
	// END EXTRA CODE
}
